version: "3.10"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies

  movie-recommender:
    build: .
    environment:
      PROJECT_NAME: "movie_recommender"
      PYTHONPATH: .:app
      POSTGRES_URI: "postgresql://postgres:postgres@db:5432/movies"
      FORCE_IMPORT: "${FORCE_IMPORT}"
    ports:
      - "8383:8000"
    command: bash start.sh
    links:
      - "db"
    volumes:
      - ./data:/home/data
