version: "3.10"
services:
  app :
    build: .
    environment:
      EXTERNAL_PORT: 8383
      LOG_LEVEL: "INFO"
      PROJECT_NAME: "movie_recommender"
    ports:
      - "8383:8000"

  db:
    image: postgres:latest
    ports:
       - "5401:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
